# Setup
title:               Woosung Choi
tagline:             'ws-choi'
description:         Woosung Choi's blog
url:                 https://ws-choi.github.io/
baseurl:             'blog-kor'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Woosung choi
  url:               https://twitter.com/
  email:             ws_choi@korea.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
